GET http://localhost:5018/games
###
GET http://localhost:5018/games/2

###
POST http://localhost:5018/games
Content-Type: application/json

{
    "Name": "Street Fighter II",
    "GenreId": 1,
    "Price": 9.92,
    "ReleaseDate": "1991-04-02"
}

###
PUT http://localhost:5018/games/1
Content-Type: application/json

{
    "Name": "Street Fighter II Turbo",
    "GenreId": 1,
    "Price": 9.92,
    "ReleaseDate": "1991-04-02"
}
###
DELETE http://localhost:5018/games/1

### 

GET http://localhost:5018/genres